### ISSUE TITLE
Levels to the game

### ISSUE THREAD

**Issue by redzaroslii** [ijbeol/ijbeol#2]
This game is too difficult and should allow for users of different skill levels.

Please implement a feature that allows for different levels. This basically means different `gave.txt` files. The implementation should be an input box at the start that says: "Please select level by responding with either of the options [Level 1, Level 2, Level 3]."  

"Level 1" should correspond with `gave_level_1.txt` etc.

**Comment by ijbeol** [comment]
Thank you for your input Redza Rosli Cognite. I will fix that asap.

**Comment by ijbeol** [comment]
Good evening Redza Rosli Cognite. I'm happy to inform you that your suggested feature has been added to the game. Please try it out :)
